# Generated by Django 4.1.6 on 2024-05-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetableapp", "0004_auto_20200814_1842"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="activity_type",
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="class",
            name="week_day",
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="classcourse",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="classroom_type",
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_type",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="sectionclassroom",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
